### ISSUE TITLE
Use global resource costs when check for sufficient & subtract

### ISSUE THREAD

**Issue by sschrijver** [SanderBouwman/ConstructAndDestroy#122]
Now the building is responsible for its own costs.
In branch #feat/extra-info the costs are added to a buildingtype,
we should use this when checking for sufficient resources and subtracting resources.

**Comment by JeroenVinke** [comment]
In [these constructors](https://github.com/SanderBouwman/ConstructAndDestroy/blob/development/src/logic/entity/static/building/building_entity.cpp#L11-L34) we know what the buildingtype is. In these constructors, can we figure out what the cost is and set it in the cost field of the BuildingEntity?
