### ISSUE TITLE
Select Group of Workers

### ISSUE THREAD

**Issue by MarkVlamPersie** [SanderBouwman/ConstructAndDestroy#21]

**Comment by MarkVlamPersie** [comment]
Paar problemen na het mergen... wordt gefixt na de vakantie.
Werkend:
https://gyazo.com/6ea110976981053f8b025006539998d5
https://gyazo.com/2e7b36046b6cd14ff87a6ff0e991994b

**Comment by JeroenVinke** [comment]
Supervet!

**Comment by JeroenVinke** [comment]
Ik ben net begonnen met controlling workers. Heb jouw branch gepakt en ik denk dat ik prima uit de voeten kan :+1:
