### ISSUE TITLE
Create a GUI

### ISSUE THREAD

**Issue by MarkVlamPersie** [SanderBouwman/ConstructAndDestroy#25]

**Comment by MarkVlamPersie** [comment]
Iniate GUI. Make panel, make something with buttons. Must be Reusable and extendable so that it can be implemented on things later like buildings and units.

**Comment by Rboin** [comment]
Reimplemented the UI, callback system and rendering. 
Examples on how to create panels/windows/buttons and hook them up to the callback system can be sound [here](https://github.com/SanderBouwman/ConstructAndDestroy/blob/development/src/ui/main.cpp).
