### ISSUE TITLE
delta time bug in ordering units from castle.

### ISSUE THREAD

**Issue by MarkVlamPersie** [SanderBouwman/ConstructAndDestroy#87]
there is a bug that resets the delta_time on every order. For example: so if you place a new order at 9 seconds waiting, you will have to wait another 10 seconds. 

Will fix this after finishing documentation.

**Comment by MarkVlamPersie** [comment]
there is a bug that resets the delta_time on every order. For example: so if you place a new order at 9 seconds waiting, you will have to wait another 10 seconds. 

Will fix this after finishing documentation.

**Comment by JeroenVinke** [comment]
@MarkVlamPersie did we fix this?
